### ISSUE TITLE
No README.md file

### ISSUE THREAD

**Issue by E-fais** [himanshu1221/Movie-Website#1]
### Description

I noticed that this repository does not have a README file, which could make it difficult for users to understand the purpose and usage of the project. It would be helpful to have a README file that provides relevant information, such as:

Project overview
Installation instructions
Usage instructions
Contribution guidelines
License information
Contact information or links to documentation
A well-written README file can greatly improve the usability and adoption of the project, and make it more welcoming to new users and contributors.

**Comment by shrijit37** [comment]
hey Himanshu, I would like to update the readme file if you're not currently working on it.

**Comment by E-fais** [comment]
@himanshu1221

**Comment by himanshu1221** [comment]
> @himanshu1221 

Hey @E-fais go ahead assigning in chronological order

**Comment by himanshu1221** [comment]
closing as completed
